import { useEffect, useState } from 'react'
import { Check, FileText, Shield, X } from 'lucide-react'

export default function AdminVerification() {
  const [responders, setResponders] = useState([])
  const [message, setMessage] = useState('')
  async function load() { const response = await fetch('/api/responders'); const result = await response.json(); setResponders(result.responders || []) }
  useEffect(() => { load() }, [])
  async function decide(id, decision) { const response = await fetch(`/api/responders/${id}/verification`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ decision }) }); const result = await response.json(); if (!response.ok) setMessage(result.error); else { setMessage(`Responder ${decision === 'verify' ? 'verified' : 'rejected'}.`); load() } }
  return <section><div className="mb-8 flex items-end justify-between gap-4"><div><p className="eyebrow">Admin console</p><h1 className="mt-2 text-3xl font-bold text-slate-950">Responder verification</h1><p className="mt-2 text-sm text-slate-600">Review prototype submissions before responders can receive alerts.</p></div><div className="icon-box"><Shield className="size-5" /></div></div>{message && <p className="mb-4 text-sm font-medium text-emerald-700">{message}</p>}<div className="table-wrap"><table><thead><tr><th>Name</th><th>Role</th><th>Qualification / College</th><th>Status</th><th>Document</th><th>Decision</th></tr></thead><tbody>{responders.map((responder) => <tr key={responder.id}><td className="font-semibold text-slate-950">{responder.name}</td><td>{responder.role}</td><td>{responder.qualification}</td><td><span className={`badge ${responder.verification_status}`}>{responder.verification_status}</span></td><td><a className="flex items-center gap-2 text-xs text-slate-700 underline" href={`/api/responders/${responder.id}/document`} target="_blank" rel="noreferrer"><FileText className="size-4" />{responder.document_filename}</a></td><td><div className="flex gap-2"><button className="table-button verify" type="button" title="Verify responder" onClick={() => decide(responder.id, 'verify')}><Check className="size-4" />Verify</button><button className="table-button reject" type="button" title="Reject responder" onClick={() => decide(responder.id, 'reject')}><X className="size-4" />Reject</button></div></td></tr>)}</tbody></table>{!responders.length && <p className="p-8 text-center text-sm text-slate-500">No responder registrations yet.</p>}</div></section>
}