import { useEffect, useState } from 'react'
import { Check, LogIn, MapPin, Radio, RefreshCw, X } from 'lucide-react'
import EmergencyMap from './EmergencyMap'

export default function ResponderDashboard({ responder }) {
  const [available, setAvailable] = useState(Boolean(responder?.available))
  const [emergencies, setEmergencies] = useState([])
  const [acceptedEmergency, setAcceptedEmergency] = useState(null)
  const [message, setMessage] = useState('')
  const responderId = responder?.id || Number(localStorage.getItem('responderId'))
  async function load(latitude, longitude) { if (!responderId) return; const locationQuery = Number.isFinite(latitude) && Number.isFinite(longitude) ? `&latitude=${latitude}&longitude=${longitude}` : ''; const response = await fetch(`/api/responder/emergencies?responder_id=${responderId}${locationQuery}`); const result = await response.json(); if (response.ok) setEmergencies(result.emergencies || []); else setMessage(result.error) }
  useEffect(() => { if (!responderId) return; if (navigator.geolocation) navigator.geolocation.getCurrentPosition(({ coords }) => load(coords.latitude, coords.longitude), () => load()); else load() }, [responderId])
  async function toggleAvailability() { const next = !available; const response = await fetch(`/api/responders/${responderId}/availability`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ available: next }) }); const result = await response.json(); if (!response.ok) setMessage(result.error); else setAvailable(Boolean(result.responder.available)) }
  async function decide(id, action) { const endpoint = action === 'accept' ? 'accept' : 'reject'; const body = action === 'accept' ? { responder_id: responderId } : {}; const response = await fetch(`/api/emergencies/${id}/${endpoint}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) setMessage(result.error); else { setMessage(action === 'accept' ? `Alert #${id} accepted. Navigation is ready.` : `Alert #${id} rejected.`); if (action === 'accept') setAcceptedEmergency(result.emergency); load() } }
  return <section><div className="mb-8 flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">Responder workspace</p><h1 className="mt-2 text-3xl font-bold text-slate-950">Alerts nearby</h1><p className="mt-2 text-sm text-slate-600">{responder?.name ? `Welcome, ${responder.name}.` : 'Select a verified responder to continue.'}</p></div><button className={`availability ${available ? 'online' : ''}`} type="button" onClick={toggleAvailability} disabled={!responderId}><span className="status-dot" />{available ? 'Online' : 'Offline'}</button></div>{message && <p className="mb-5 flex items-center gap-2 text-sm font-medium text-emerald-700"><Check className="size-4" />{message}</p>}{acceptedEmergency && <div className="mb-5 flex items-center justify-between gap-4 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm"><span>Navigation to alert #{acceptedEmergency.id} is ready.</span><a className="table-button verify" href={`https://www.google.com/maps/dir/?api=1&destination=${acceptedEmergency.latitude},${acceptedEmergency.longitude}`} target="_blank" rel="noreferrer"><LogIn className="size-4" />Navigate</a></div>}<div className="grid gap-6 xl:grid-cols-[1fr_1.1fr]"><div className="space-y-4">{emergencies.map((emergency) => <article className="alert-item" key={emergency.id}><div className="flex items-start justify-between gap-3"><div><span className="badge alert">{emergency.emergency_type}</span><h2 className="mt-3 text-lg font-bold text-slate-950">Emergency alert #{emergency.id}</h2></div><Radio className="size-5 text-[#df4d38]" /></div><p className="mt-2 text-sm text-slate-600">{emergency.description || 'No additional description.'}</p><div className="mt-4 flex items-center gap-2 text-xs text-slate-500"><MapPin className="size-4" />{emergency.distance_km === null ? 'Distance unavailable' : `Approximately ${emergency.distance_km} km away`}</div><div className="mt-5 flex gap-2"><button className="table-button verify" type="button" onClick={() => decide(emergency.id, 'accept')} disabled={!available}><Check className="size-4" />Accept</button><button className="table-button reject" type="button" onClick={() => decide(emergency.id, 'reject')}><X className="size-4" />Reject</button></div></article>)}{!emergencies.length && <div className="surface p-10 text-center"><RefreshCw className="mx-auto size-6 text-slate-400" /><p className="mt-3 text-sm text-slate-500">No active alerts at the moment.</p></div>}</div><div className="map-shell"><EmergencyMap emergencies={emergencies} /></div></div></section>
}